services:
  server:
    depends_on:
      - db
    build:
      context: .
      dockerfile: ./Dockerfile-development
    ports:
      - ${SERVER_PORT:-3000}:${SERVER_PORT:-3000}
    environment:
      - NODE_ENV=development
      - SECRET=${SECRET:-dev_secret}
      - SERVER_PORT=${SERVER_PORT:-3000}
      - POSTGRES_HOST=${POSTGRES_HOST:-db}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - POSTGRES_DB=${POSTGRES_DB:-xsweet_dev_db}
      - POSTGRES_USER=${POSTGRES_USER:-xsweet_user_dev}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-secretpassword}
    command: ['yarn', 'coko-server', 'start-dev']
    volumes:
      - ./server:/home/node/xsweet/server
      - ./config:/home/node/xsweet/config

  db:
    image: postgres:16-alpine
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-xsweet_dev_db}
      - POSTGRES_USER=${POSTGRES_USER:-xsweet_user_dev}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-secretpassword}
